#ifndef ASSET_IDS_H
#define ASSET_IDS_H

// Auto-generated asset ID constants
// Generated by AssetIdGenerator tool

#include <cstdint>

namespace Assets
{

    using AssetId = uint32_t;

    // Asset ID constants
    constexpr AssetId DEVELOPERPACKAGE_DEMO_TEXTURE = 1;  // texture from DeveloperPackage
    constexpr AssetId DEVELOPERPACKAGE_DEMO_MESH = 2;     // mesh from DeveloperPackage
    constexpr AssetId DEVELOPERPACKAGE_DEMO_MATERIAL = 3; // material from DeveloperPackage
    constexpr AssetId DEVELOPERPACKAGE_DEMO_SHADER = 4;   // shader from DeveloperPackage

} // namespace Assets

#endif // ASSET_IDS_H
